# QA-ManualPress: authored control blurbs, merged into the generated Controls
# tables by generate-manual.py.  Keys are the control's param id (from
# bsd-docs.json); controls with no id key on "<figure name>|<label>", with
# "#2"/"#3" ordinals when sibling stages reuse a label (walk order = stage
# order, so Vocal Chain runs Gate, De-reverb, De-esser, Compressor,
# Saturation, Limiter).
# Register rules (batch plan "shutter-snapping-shrike"): verb-first, 3-9
# words, effect first, numbers live in the Range/Default columns, never here.
BLURBS = {
    # ── BaySickSynth / BaySickBass shared voice controls ──────────────────
    "tk_lay_0_bss_transpose":      "Shifts pitch in semitone steps.",
    "tk_lay_0_bss_modifier":       "Shapes the wave; meaning follows the waveform mode.",
    "tk_lay_0_bss_noise":          "Blends noise into the oscillator.",
    "tk_lay_0_bss_glide":          "Slides pitch between consecutive notes.",
    "tk_lay_0_bss_outVol":         "Sets this engine's output level.",
    "tk_lay_0_bss_modWheelAmt":    "Scales how far the mod wheel reaches.",
    "tk_bas_0_bsb_transpose":      "Shifts pitch in semitone steps.",
    "tk_bas_0_bsb_modifier":       "Shapes the wave; meaning follows the waveform mode.",
    "tk_bas_0_bsb_noise":          "Blends noise into the oscillator.",
    "tk_bas_0_bsb_glide":          "Slides pitch between consecutive notes.",
    "tk_bas_0_bsb_outVol":         "Sets this engine's output level.",
    "tk_bas_0_bsb_modWheelAmt":    "Scales how far the mod wheel reaches.",

    # ── BaySickSynth OSC ENV ──────────────────────────────────────────────
    "tk_lay_0_bss_amp_attack":     "Sets how fast a note fades in.",
    "tk_lay_0_bss_amp_decay":      "Sets the fall time after the attack peak.",
    "tk_lay_0_bss_amp_sustain":    "Holds this level while the key is down.",
    "tk_lay_0_bss_amp_release":    "Sets the fade-out after the key lifts.",
    "tk_lay_0_bss_velAmpTrack":    "Maps key velocity onto note volume.",
    "tk_lay_0_bss_pEnv_attack":    "Sets the pitch envelope's rise time.",
    "tk_lay_0_bss_pEnv_decay":     "Sets the pitch envelope's fall time.",
    "tk_lay_0_bss_pEnv_sustain":   "Holds the pitch offset while the key is down.",
    "tk_lay_0_bss_pEnv_release":   "Sets the pitch envelope's release time.",
    "tk_lay_0_bss_pEnv_amt":       "Sets how far the envelope bends pitch.",

    # ── BaySickSynth FLT / FLT ENV ────────────────────────────────────────
    "tk_lay_0_bss_flt_kbtrack":    "Raises the cutoff with higher keys.",
    "tk_lay_0_bss_flt_veltrack":   "Opens the filter with harder velocity.",
    "tk_lay_0_bss_flt_attack":     "Sets the filter envelope's rise time.",
    "tk_lay_0_bss_flt_decay":      "Sets the filter envelope's fall time.",
    "tk_lay_0_bss_flt_sustain":    "Holds the filter envelope at this level.",
    "tk_lay_0_bss_flt_release":    "Sets the filter envelope's release time.",
    "tk_lay_0_bss_flt_env_amt":    "Sets how far the envelope moves the cutoff.",

    # ── BaySickSynth LFO ──────────────────────────────────────────────────
    "tk_lay_0_bss_lfo_rate":       "Sets the LFO's cycle speed.",
    "tk_lay_0_bss_lfo_amount":     "Sets how deep the LFO modulates.",

    # ── BaySickSynth MOD ──────────────────────────────────────────────────
    "tk_lay_0_bss_trans_amount":   "Adds a click of noise at note start.",
    "tk_lay_0_bss_trans_duration": "Sets how long the start click lasts.",
    "tk_lay_0_bss_trans_colour":   "Brightens or darkens the start click.",
    "tk_lay_0_bss_unison_voices":  "Stacks copies of the voice for thickness.",
    "tk_lay_0_bss_unison_detune":  "Spreads the stacked voices in pitch.",
    "tk_lay_0_bss_unison_spread":  "Spreads the stacked voices across stereo.",
    "tk_lay_0_bss_drift":          "Adds slow per-voice pitch wander.",
    "tk_lay_0_bss_burst_count":    "Fires this many retriggers per note.",
    "tk_lay_0_bss_burst_spacing":  "Sets the gap between burst retriggers.",

    # ── BaySickPlayer ─────────────────────────────────────────────────────
    "tk_lay_2_bsp_sampleStart":    "Skips into the sample before playback.",
    "tk_lay_2_bsp_stretch":        "Speeds up or slows down playback.",
    "tk_lay_2_bsp_reverse":        "Plays the sample backwards.",
    "tk_lay_2_bsp_cutSelf":        "Cuts the prior voice on the same note.",
    "tk_lay_2_bsp_cutSelfMode":    "Picks what a retrigger cuts.",
    "tk_lay_2_bsp_tune":           "Shifts pitch in semitone steps.",
    "tk_lay_2_bsp_voiceCap":       "Caps how many notes sound at once.",
    "tk_lay_2_bsp_unisonVoices":   "Stacks copies of the voice for thickness.",
    "tk_lay_2_bsp_detune":         "Offsets pitch in cents.",
    "tk_lay_2_bsp_unisonSpread":   "Spreads the stacked voices in pitch.",
    "tk_lay_2_bsp_sensitivity":    "Shapes how velocity maps to response.",
    "tk_lay_2_bsp_velToVolume":    "Maps key velocity onto note volume.",
    "tk_lay_2_bsp_velToMuffle":    "Maps key velocity onto muffle.",
    "tk_lay_2_bsp_muffle":         "Darkens the sample with a low-pass.",
    "tk_lay_2_bsp_velToHardness":  "Maps key velocity onto hardness.",
    "tk_lay_2_bsp_hardness":       "Adds filter resonance for bite.",
    "tk_lay_2_bsp_attack":         "Sets how fast a note fades in.",
    "tk_lay_2_bsp_decay":          "Sets the fall time after the attack peak.",
    "tk_lay_2_bsp_sustain":        "Holds this level while the key is down.",
    "tk_lay_2_bsp_release":        "Sets the fade-out after the key lifts.",
    "tk_lay_2_bsp_lfo_rate":       "Sets how fast the pitch wobbles.",
    "tk_lay_2_bsp_lfoAmt":         "Sets how far the pitch wobbles.",
    "tk_lay_2_bsp_cutoff":         "Sets the filter's corner frequency.",
    "tk_lay_2_bsp_res":            "Boosts the filter's corner for bite.",
    "tk_lay_2_bsp_reduct":         "Adds lo-fi sample-rate grit.",
    "tk_lay_2_bsp_pan":            "Places the sound left or right.",
    "tk_lay_2_bsp_stereo":         "Narrows or widens the stereo image.",
    "tk_lay_2_bsp_treble":         "Cuts or boosts the high shelf.",
    "tk_lay_2_bsp_drive":          "Adds overdrive saturation.",
    "tk_lay_2_bsp_volume":         "Sets this engine's output level.",

    # ── BaySickSolstice ──────────────────────────────────────────────────────────
    "tk_lay_1_bso_flt1_type":     "Picks filter 1's shape.",
    "tk_lay_1_bso_flt_env_amt":   "Sets how far the envelope moves filter 1.",
    "tk_lay_1_bso_flt_cutoff":    "Sets filter 1's corner frequency.",
    "tk_lay_1_bso_flt_res":       "Boosts filter 1's corner for bite.",
    "tk_lay_1_bso_flt1_kb_track": "Raises filter 1's cutoff with higher keys.",
    "tk_lay_1_bso_flt2_type":     "Picks filter 2's shape.",
    "tk_lay_1_bso_flt2_env_amt":  "Sets how far the envelope moves filter 2.",
    "tk_lay_1_bso_flt2_cutoff":   "Sets filter 2's corner frequency.",
    "tk_lay_1_bso_flt2_res":      "Boosts filter 2's corner for bite.",
    "tk_lay_1_bso_flt2_kb_track": "Raises filter 2's cutoff with higher keys.",
    "tk_lay_1_bso_rm_sub":        "Routes the sub oscillator into the mix.",
    "tk_lay_1_bso_rm_prot":       "Routes the protect stage into the mix.",
    "tk_lay_1_bso_rm_clip":       "Routes the clip stage into the mix.",
    "tk_lay_1_bso_rm_fx":         "Routes the FX stage into the mix.",
    "tk_lay_1_bso_rm_vol":        "Routes the volume stage into the mix.",
    "tk_lay_1_bso_rm_env":        "Routes the envelope stage into the mix.",
    "tk_lay_1_bso_mod_x":         "Drives the modulation pad's X axis.",
    "tk_lay_1_bso_mod_y":         "Drives the modulation pad's Y axis.",
    "tk_lay_1_bso_mod_z":         "Drives the modulation pad's Z axis.",
    "tk_lay_1_bso_timbre_blend":  "Crossfades Part A toward Part B.",
    "tk_lay_1_bso_partA_level":   "Sets Part A's level.",
    "tk_lay_1_bso_partB_level":   "Sets Part B's level.",
    "tk_lay_1_bso_brownian_amount": "Rolls the spectrum off toward brown noise.",
    "tk_lay_1_bso_blur_size":     "Smears the spectrum for a washed tone.",
    "tk_lay_1_bso_blur_time":     "Widens the blur kernel over time.",
    "tk_lay_1_bso_blur_harm":     "Biases the blur along the harmonic axis.",
    "tk_lay_1_bso_prism_amount":  "Spreads partials away from harmonic pitch.",
    "tk_lay_1_bso_prism_mode":    "Picks how prism scatters the partials.",
    "tk_lay_1_bso_trem_depth":    "Sets how deep the volume pulses.",
    "tk_lay_1_bso_trem_speed":    "Sets how fast the volume pulses.",
    "tk_lay_1_bso_trem_gap":      "Widens the dead zone between pulses.",
    "tk_lay_1_bso_vib_depth":     "Sets how far the pitch wobbles.",
    "tk_lay_1_bso_vib_speed":     "Sets how fast the pitch wobbles.",
    "tk_lay_1_bso_vib_env":       "Delays vibrato onset after note start.",
    "tk_lay_1_bso_glide_time":    "Slides pitch between consecutive notes.",
    "tk_lay_1_bso_legato_limit":  "Caps the longest glide time.",
    "tk_lay_1_bso_flt1_cutoff_ofs": "Offsets filter 1's cutoff in semitones.",
    "tk_lay_1_bso_flt2_cutoff_ofs": "Offsets filter 2's cutoff in semitones.",
    "tk_lay_1_bso_filter_mask_cutoff": "Caps which harmonics Part A passes.",
    "tk_lay_1_bso_partB_filter_mask_cutoff": "Caps which harmonics Part B passes.",
    "tk_lay_1_bso_flt_a":         "Sets filter 1 envelope's rise time.",
    "tk_lay_1_bso_flt_d":         "Sets filter 1 envelope's fall time.",
    "tk_lay_1_bso_flt_s":         "Holds filter 1's envelope at this level.",
    "tk_lay_1_bso_flt_r":         "Sets filter 1 envelope's release time.",
    "tk_lay_1_bso_flt2_a":        "Sets filter 2 envelope's rise time.",
    "tk_lay_1_bso_flt2_d":        "Sets filter 2 envelope's fall time.",
    "tk_lay_1_bso_flt2_s":        "Holds filter 2's envelope at this level.",
    "tk_lay_1_bso_flt2_r":        "Sets filter 2 envelope's release time.",
    "tk_lay_1_bso_lfo_rate":      "Sets the cycle length every LFO target shares.",
    "tk_lay_1_bso_lfo_shape":     "Picks the shared LFO waveform.",
    "tk_lay_1_bso_legato":        "Retriggers nothing on overlapped notes.",
    "tk_lay_1_bso_unison_voices": "Stacks copies of the voice for thickness.",
    "tk_lay_1_bso_unison_type":   "Picks how the stacked voices detune.",
    "tk_lay_1_bso_unison_alt":    "Alternates unison phases per note.",
    "tk_lay_1_bso_unison_spread": "Spreads the stacked voices across stereo.",
    "tk_lay_1_bso_unison_detune": "Spreads the stacked voices in cents.",
    "tk_lay_1_bso_unison_phase":  "Offsets the stacked voices' start phase.",
    "tk_lay_1_bso_pluck_decay":   "Speeds the decay of high partials.",
    "tk_lay_1_bso_ophaser_mix":   "Blends the output phaser in.",
    "tk_lay_1_bso_ophaser_depth": "Deepens the output phaser's sweep.",
    "tk_lay_1_bso_ophaser_rate":  "Sets the output phaser's sweep speed.",
    "tk_lay_1_bso_ophaser_width": "Feeds the phaser back into itself.",
    "tk_lay_1_bso_ophaser_ofs":   "Centers the phaser's sweep frequency.",
    "tk_lay_1_bso_phaser_mask_rate": "Spaces the phaser's spectral notches.",
    "tk_lay_1_bso_oeq_mix":       "Blends the output tilt EQ in.",
    "tk_lay_1_bso_pluck_blur":    "Softens the pluck with spectral blur.",
    "tk_lay_1_bso_pitch_semitones": "Shifts pitch in semitone steps.",
    "tk_lay_1_bso_pitch_cents":   "Offsets pitch in cents.",
    "tk_lay_1_bso_pitch_freq_frac": "Multiplies or divides the pitch by octaves.",
    "tk_lay_1_bso_volume":        "Sets this engine's output level.",
    "tk_lay_1_bso_pan":           "Places the sound left or right.",
    "tk_lay_1_bso_vel_link":      "Links note velocity into the mod chain.",
    "tk_lay_1_bso_cutSelf":       "Cuts the prior voice on the same note.",
    "tk_lay_1_bso_cutSelfMode":   "Picks what a retrigger cuts.",
    "tk_lay_1_bso_amp_a":         "Sets how fast a note fades in.",
    "tk_lay_1_bso_amp_d":         "Sets the fall time after the attack peak.",
    "tk_lay_1_bso_amp_s":         "Holds this level while the key is down.",
    "tk_lay_1_bso_amp_r":         "Sets the fade-out after the key lifts.",
    "tk_lay_1_bso_phase_start":   "Sets where the wave cycle starts.",
    "tk_lay_1_bso_phase_rand":    "Randomizes the start phase per note.",
    "tk_lay_1_bso_lfo_vel":       "Scales LFO depth by note velocity.",
    "tk_lay_1_bso_lfo_vol":       "Sends the shared LFO to volume.",
    "tk_lay_1_bso_lfo_pitch":     "Sends the shared LFO to pitch.",
    "tk_lay_1_bso_strum_dir":     "Picks which way chords strum.",
    "tk_lay_1_bso_strum_time":    "Staggers chord notes across this time.",
    "tk_lay_1_bso_strum_tns":     "Curves the strum toward start or end.",
    "tk_lay_1_bso_volume_mod0_depth": "Sets the modulation envelope's strength.",
    "tk_lay_1_bso_volume_mod0_length": "Sets the modulation envelope's play length.",

    # ── BaySickVocals ─────────────────────────────────────────────────────
    "bsv_ab_slot":                 "Switches between the A and B settings slots.",
    "bsv_pitch_realtime_bypass":   "Turns realtime pitch correction on.",
    "bsv_pitch_key":               "Picks the root note correction pulls to.",
    "bsv_pitch_scale":             "Picks the scale correction snaps to.",
    "bsv_pitch_retuneSpeed":       "Sets how fast pitch snaps to the note.",
    "bsv_pitch_strength":          "Sets how hard correction pulls the pitch.",
    "bsv_pitch_humanize":          "Adds small random wobble after correction.",
    "bsv_pitch_throatShift":       "Shifts vocal resonance apart from pitch.",
    "bsv_pitch_formantPreserve":   "Keeps the voice's character while shifting.",

    # ── BaySickNAMIR ──────────────────────────────────────────────────────
    "input_gain":                  "Sets the level hitting the amp model.",
    "gate_threshold":              "Silences signal below this level.",
    "gate_release":                "Sets how fast the gate closes.",
    "low_cut":                     "Tightens the low end before the cab.",
    "high_cut":                    "Tames fizz before the cab.",
    "cab_mix":                     "Blends the cabinet simulation in.",
    "output":                      "Sets the final output level.",
    "BaySickNAMIR|Mix":            "Blends the mic simulation in.",
    "BaySickNAMIR|Distance":       "Moves the virtual mic closer or farther.",
    "BaySickNAMIR|Angle":          "Turns the virtual mic off axis.",
    "BaySickNAMIR|Height":         "Raises the virtual mic off cone center.",

    # ── BaySickPedals (tuner + graphic EQ tiles) ──────────────────────────
    "BaySickPedals|Trim":          "Fine-trims the tuner's reference pitch.",
    "BaySickPedals|Dist":          "Adds cascading hard-clip distortion.",
    "BaySickPedals|Low":           "Cuts or boosts the low shelf.",
    "BaySickPedals|Mid Hz":        "Moves the mid peak's frequency.",
    "BaySickPedals|Mid dB":        "Cuts or boosts the mid peak.",
    "BaySickPedals|High":          "Cuts or boosts the high shelf.",
    "BaySickPedals|Level":         "Sets the pedal's output level.",
    "BaySickPedals Compact View|Trim": "Fine-trims the tuner's reference pitch.",

    # ── EQ (per-band rail; ids name band 2, every band matches) ──────────
    "mixer_master_preeq_b1Gain":      "Sets this band's boost or cut.",
    "mixer_master_preeq_b1Sat":       "Saturates just this band's slice.",
    "mixer_master_preeq_b1Place":     "Pans this band's effect across stereo.",
    "mixer_master_preeq_b1Threshold": "Engages the band above this level.",
    "mixer_master_preeq_b1Ratio":     "Sets how hard the band moves past threshold.",
    "mixer_master_preeq_b1Attack":    "Sets the detector's reaction speed.",
    "mixer_master_preeq_b1Release":   "Sets the detector's recovery speed.",
    "mixer_master_preeq_b1ThresholdB": "Engages the below stage under this level.",
    "mixer_master_preeq_b1RatioB":    "Sets how hard the below stage moves.",
    "mixer_master_preeq_b1RangeB":    "Sets the below stage's travel and direction.",
    "mixer_master_preeq_b1Onset":     "Focuses the detector on attacks only.",
    "mixer_master_preeq_b1LfoRate":   "Sets the band LFO's speed.",
    "mixer_master_preeq_b1LfoDepth":  "Sets how far the LFO swings the band.",
    "mixer_master_preeq_b1EnvDepth":  "Rides or ducks the band with its level.",
    "mixer_master_preeq_b1Freq":      "Sets the band's center frequency.",
    "mixer_master_preeq_b1Q":         "Narrows or widens the band.",
    "mixer_master_preeq_b1Type":      "Picks the band's curve shape.",
    "mixer_master_preeq_b1Slope":     "Steepens the pass filter's rolloff.",

    # ── Effects Panel (De-esser) ──────────────────────────────────────────
    "master_54c97cd556b44e05a7443be8a26cb3b0_output_vol": "Sets the slot's output level.",
    "master_54c97cd556b44e05a7443be8a26cb3b0_detect":     "Widens what counts as an S sound.",
    "master_54c97cd556b44e05a7443be8a26cb3b0_thresh":     "Triggers reduction above this level.",
    "master_54c97cd556b44e05a7443be8a26cb3b0_range":      "Caps how much the de-esser pulls down.",
    "master_54c97cd556b44e05a7443be8a26cb3b0_mode":       "Morphs from wide ducking to split-band.",

    # ── Effects Panel with Visual (Reverb) ────────────────────────────────
    "master_621e60bbafc540aaae7e8ecb187602af_output_vol": "Sets the slot's output level.",
    "master_621e60bbafc540aaae7e8ecb187602af_room":    "Scales the modeled room's size.",
    "master_621e60bbafc540aaae7e8ecb187602af_decay":   "Sets how long the tail rings.",
    "master_621e60bbafc540aaae7e8ecb187602af_hfratio": "Shortens or extends the high tail.",
    "master_621e60bbafc540aaae7e8ecb187602af_diffuse": "Thickens the reverb's early density.",
    "master_621e60bbafc540aaae7e8ecb187602af_predly":  "Delays the reverb after the dry sound.",
    "master_621e60bbafc540aaae7e8ecb187602af_wettone": "Tilts the wet signal warm or bright.",
    "master_621e60bbafc540aaae7e8ecb187602af_wet":     "Sets the reverb level.",
    "master_621e60bbafc540aaae7e8ecb187602af_dry":     "Sets the untouched signal's level.",
    "master_621e60bbafc540aaae7e8ecb187602af_locut":   "Cuts lows entering the reverb.",
    "master_621e60bbafc540aaae7e8ecb187602af_hicut":   "Cuts highs entering the reverb.",
    "master_621e60bbafc540aaae7e8ecb187602af_bassmlt": "Lengthens or shortens the bass tail.",
    "master_621e60bbafc540aaae7e8ecb187602af_bassx":   "Sets where the bass tail takes over.",
    "master_621e60bbafc540aaae7e8ecb187602af_taildep": "Deepens the tail's slow movement.",
    "master_621e60bbafc540aaae7e8ecb187602af_tailrt":  "Sets the tail movement's speed.",
    "master_621e60bbafc540aaae7e8ecb187602af_stereo":  "Separates the reverb's left and right.",
    "master_621e60bbafc540aaae7e8ecb187602af_hidamp":  "Darkens the tail above this frequency.",
    "master_621e60bbafc540aaae7e8ecb187602af_er":      "Sets the early reflections' level.",
    "master_621e60bbafc540aaae7e8ecb187602af_freeze":  "Holds the current tail forever.",
    "master_621e60bbafc540aaae7e8ecb187602af_duck":    "Ducks the wet under the trigger signal.",
    "master_621e60bbafc540aaae7e8ecb187602af_dkthr":   "Starts ducking above this trigger level.",
    "master_621e60bbafc540aaae7e8ecb187602af_dkatt":   "Sets how fast the wet ducks.",
    "master_621e60bbafc540aaae7e8ecb187602af_dkrel":   "Sets how fast the wet recovers.",

    # ── Mixer ─────────────────────────────────────────────────────────────
    "mixer_master_pan":     "Places the strip left or right.",
    "mixer_master_fader":   "Sets the strip's level.",
    "mixer_bass_pan":       "Places the strip left or right.",
    "mixer_bass_fader":     "Sets the strip's level.",
    "mixer_fx_pan":         "Places the strip left or right.",
    "mixer_fx_fader":       "Sets the strip's level.",
    "mixer_bass_0_pan":     "Places the strip left or right.",
    "mixer_bass_0_fader":   "Sets the strip's level.",
    "mixer_master_width":   "Narrows or widens the strip's stereo image.",
    "mixer_master_mute":    "Silences the strip.",
    "mixer_voxbus_pan":     "Places the strip left or right.",
    "mixer_voxbus_fader":   "Sets the strip's level.",
    "mixer_instbus_pan":    "Places the strip left or right.",
    "mixer_instbus_fader":  "Sets the strip's level.",
    "mixer_vox_0_pan":      "Places the strip left or right.",
    "mixer_vox_0_fader":    "Sets the strip's level.",
    "mixer_inst_0_pan":     "Places the strip left or right.",
    "mixer_inst_0_fader":   "Sets the strip's level.",

    # ── Vocal Chain (stage order: Gate, De-reverb, De-esser, Compressor,
    #    Saturation, Limiter; '#n' = later stage reusing a label) ─────────
    "Vocal Chain|Vol":      "Sets this stage's output level.",
    "Vocal Chain|Thresh":   "Closes the gate below this level.",
    "Vocal Chain|Range":    "Sets how deep the closed gate cuts.",
    "Vocal Chain|Attack":   "Sets how fast the gate opens.",
    "Vocal Chain|Hold":     "Holds the gate open after signal drops.",
    "Vocal Chain|Release":  "Sets how fast the gate closes.",
    "Vocal Chain|Reduce":   "Suppresses the recorded room tail.",
    "Vocal Chain|Tail":     "Matches the modeled tail to the room.",
    "Vocal Chain|Mix":      "Blends the de-reverbed signal in.",
    "Vocal Chain|Detect":   "Widens what counts as an S sound.",
    "Vocal Chain|Thresh#2": "Triggers de-essing above this level.",
    "Vocal Chain|Range#2":  "Caps how much the de-esser pulls down.",
    "Vocal Chain|Mode":     "Morphs from wide ducking to split-band.",
    "Vocal Chain|Thresh#3": "Compresses signal above this level.",
    "Vocal Chain|Ratio":    "Sets how hard compression squeezes.",
    "Vocal Chain|Gain":     "Makes up level after compression.",
    "Vocal Chain|Attack#2": "Sets how fast compression clamps.",
    "Vocal Chain|Release#2": "Sets how fast compression lets go.",
    "Vocal Chain|Drive":    "Pushes the preamp into saturation.",
    "Vocal Chain|Color":    "Adds transformer-style second harmonic.",
    "Vocal Chain|Output":   "Sets the saturation stage's output level.",
    "Vocal Chain|InGain":   "Sets the level hitting the limiter.",
    "Vocal Chain|Ceil":     "Caps the loudest output level.",
    "Vocal Chain|SatTh":    "Softens peaks before hard limiting.",
    "Vocal Chain|Atk":      "Sets how fast the limiter clamps.",
    "Vocal Chain|Rel":      "Sets how fast the limiter lets go.",
    "Vocal Chain|Sustain":  "Holds gain reduction to release musically.",

    # -- rack effect knobs.  Keyed effect + knob because a slot's param
    #    ids carry a per-run UUID: the id itself is not a stable key.
    #    Covers every effect's Basic AND Advanced panel (Jeff, 2026-08-28).
    "fx|Chorus|crosshz": "Splits which frequencies get chorused.",
    "fx|Chorus|delay": "Sets the base delay the voices sit at.",
    "fx|Chorus|depth": "Widens how far the delay sweeps.",
    "fx|Chorus|lfo1": "Sets the first sweep voice's speed.",
    "fx|Chorus|lfo2": "Sets the second sweep voice's speed.",
    "fx|Chorus|lfo3": "Sets the third sweep voice's speed.",
    "fx|Chorus|output_vol": "Sets the slot's output level.",
    "fx|Chorus|stereo": "Offsets the left and right sweeps.",
    "fx|Chorus|wet": "Sets the chorused signal's level.",
    "fx|Compressor|attack": "Sets how fast gain reduction clamps down.",
    "fx|Compressor|det": "Smooths the detector's level reading.",
    "fx|Compressor|gain": "Makes up level after compression.",
    "fx|Compressor|kneew": "Softens the transition into compression.",
    "fx|Compressor|looka": "Lets the detector see peaks early.",
    "fx|Compressor|mix": "Blends compressed against dry for parallel.",
    "fx|Compressor|output_vol": "Sets the slot's output level.",
    "fx|Compressor|ratio": "Sets how hard compression squeezes.",
    "fx|Compressor|release": "Sets how fast compression lets go.",
    "fx|Compressor|schpf": "Stops bass from triggering the detector.",
    "fx|Compressor|thresh": "Compresses signal above this level.",
    "fx|De-esser|atk": "Sets how fast the duck engages.",
    "fx|De-esser|detect": "Widens what counts as an S sound.",
    "fx|De-esser|freq": "Sets where the detector starts listening.",
    "fx|De-esser|look": "Lets the detector see the consonant early.",
    "fx|De-esser|mix": "Blends the de-essed signal in.",
    "fx|De-esser|mode": "Morphs from wide ducking to split-band.",
    "fx|De-esser|output_vol": "Sets the slot's output level.",
    "fx|De-esser|q": "Narrows the detector's listening band.",
    "fx|De-esser|range": "Caps how much the de-esser pulls down.",
    "fx|De-esser|rel": "Sets how fast the duck lets go.",
    "fx|De-esser|thresh": "Triggers de-essing above this level.",
    "fx|De-reverb|mix": "Blends the de-reverbed signal in.",
    "fx|De-reverb|output_vol": "Sets the slot's output level.",
    "fx|De-reverb|reduce": "Suppresses the recorded room tail.",
    "fx|De-reverb|tail": "Matches the modeled tail to the room.",
    "fx|Delay|diff": "Smears the repeats into a wash.",
    "fx|Delay|diffsprd": "Widens the smearing across time.",
    "fx|Delay|dkatt": "Sets how fast the repeats duck.",
    "fx|Delay|dkrel": "Sets how fast the repeats recover.",
    "fx|Delay|dkthr": "Starts ducking above this trigger level.",
    "fx|Delay|dry": "Sets the untouched signal's level.",
    "fx|Delay|duck": "Ducks the repeats under the trigger.",
    "fx|Delay|fbcut": "Filters the repeats as they recycle.",
    "fx|Delay|fbdst": "Distorts each pass through the feedback.",
    "fx|Delay|fbknee": "Shapes the feedback clip from hard to soft.",
    "fx|Delay|fbreso": "Peaks the feedback filter at its cutoff.",
    "fx|Delay|fbsym": "Skews the feedback saturation off center.",
    "fx|Delay|feed": "Sets how many times the delay repeats.",
    "fx|Delay|lobit": "Crushes the repeats' bit depth.",
    "fx|Delay|lofisr": "Downsamples the repeats for vintage grit.",
    "fx|Delay|modfb": "Sweeps the feedback filter's cutoff.",
    "fx|Delay|modhz": "Sets the modulation's speed.",
    "fx|Delay|modtime": "Sweeps the delay time for chorusing.",
    "fx|Delay|output_vol": "Sets the slot's output level.",
    "fx|Delay|pan": "Offsets the repeats left or right.",
    "fx|Delay|smooth": "Slows how fast time changes take effect.",
    "fx|Delay|spread": "Offsets the left and right delay times.",
    "fx|Delay|time": "Sets the gap between repeats.",
    "fx|Delay|tone": "Tilts the repeats dark or bright.",
    "fx|Delay|wet": "Sets the repeats' level.",
    "fx|Delay|wetin": "Sets how much new signal enters the line.",
    "fx|Flanger|cross": "Feeds each channel's sweep into the other.",
    "fx|Flanger|damp": "Darkens the feedback as it recycles.",
    "fx|Flanger|delay": "Sets the sweep's shortest delay.",
    "fx|Flanger|depth": "Widens how far the sweep travels.",
    "fx|Flanger|feed": "Sharpens the sweep by feeding it back.",
    "fx|Flanger|output_vol": "Sets the slot's output level.",
    "fx|Flanger|phase": "Offsets the right channel's sweep.",
    "fx|Flanger|rate": "Sets the sweep's speed.",
    "fx|Flanger|shape": "Morphs the sweep from sine to triangle.",
    "fx|Flanger|wet": "Blends the flanged signal in.",
    "fx|Gate|attack": "Sets how fast the gate opens.",
    "fx|Gate|hold": "Holds the gate open after signal drops.",
    "fx|Gate|output_vol": "Sets the slot's output level.",
    "fx|Gate|range": "Sets how deep the closed gate cuts.",
    "fx|Gate|release": "Sets how fast the gate closes.",
    "fx|Gate|thresh": "Closes the gate below this level.",
    "fx|Limiter|ahead": "Lets the limiter see peaks early.",
    "fx|Limiter|atk": "Sets how fast the limiter clamps.",
    "fx|Limiter|ceil": "Caps the loudest output level.",
    "fx|Limiter|ingain": "Sets the level driven into the limiter.",
    "fx|Limiter|output_vol": "Sets the slot's output level.",
    "fx|Limiter|rel": "Sets how fast the limiter lets go.",
    "fx|Limiter|relcv": "Shapes the release from linear to exponential.",
    "fx|Limiter|satcv": "Shapes the soft-saturation knee.",
    "fx|Limiter|satth": "Softens peaks before hard limiting.",
    "fx|Limiter|schpf": "Stops bass from pumping the limiter.",
    "fx|Limiter|sustain": "Holds gain reduction to release musically.",
    "fx|Overdrive|band": "Rolls off highs before the drive stage.",
    "fx|Overdrive|bias": "Skews the waveform for even harmonics.",
    "fx|Overdrive|color": "Sets where the pre-filter rolls off.",
    "fx|Overdrive|drive": "Pushes the preamp into distortion.",
    "fx|Overdrive|filter": "Tames fizz after the drive stage.",
    "fx|Overdrive|out": "Attenuates the output level.",
    "fx|Overdrive|output_vol": "Sets the slot's output level.",
    "fx|Overdrive|wet": "Blends the driven signal in.",
    "fx|Phaser|cross": "Feeds each channel's notches into the other.",
    "fx|Phaser|feed": "Sharpens the notches by feeding them back.",
    "fx|Phaser|gain": "Sets the output level.",
    "fx|Phaser|maxhz": "Sets the notch sweep's top frequency.",
    "fx|Phaser|minhz": "Sets the notch sweep's bottom frequency.",
    "fx|Phaser|output_vol": "Sets the slot's output level.",
    "fx|Phaser|rate": "Sets the sweep's speed.",
    "fx|Phaser|stereo": "Offsets the left and right sweeps.",
    "fx|Phaser|wet": "Sets the phased signal's level.",
    "fx|Reverb|bassmlt": "Lengthens or shortens the bass tail.",
    "fx|Reverb|bassx": "Sets where the bass tail takes over.",
    "fx|Reverb|decay": "Sets how long the tail rings.",
    "fx|Reverb|diffuse": "Thickens the reverb's early density.",
    "fx|Reverb|dkatt": "Sets how fast the wet ducks.",
    "fx|Reverb|dkrel": "Sets how fast the wet recovers.",
    "fx|Reverb|dkthr": "Starts ducking above this trigger level.",
    "fx|Reverb|dry": "Sets the untouched signal's level.",
    "fx|Reverb|duck": "Ducks the wet under the trigger signal.",
    "fx|Reverb|er": "Sets the early reflections' level.",
    "fx|Reverb|freeze": "Holds the current tail forever.",
    "fx|Reverb|hfratio": "Shortens or extends the high tail.",
    "fx|Reverb|hicut": "Cuts highs entering the reverb.",
    "fx|Reverb|hidamp": "Darkens the tail above this frequency.",
    "fx|Reverb|locut": "Cuts lows entering the reverb.",
    "fx|Reverb|output_vol": "Sets the slot's output level.",
    "fx|Reverb|predly": "Delays the reverb after the dry sound.",
    "fx|Reverb|room": "Scales the modeled room's size.",
    "fx|Reverb|stereo": "Separates the reverb's left and right.",
    "fx|Reverb|taildep": "Deepens the tail's slow movement.",
    "fx|Reverb|tailrt": "Sets the tail movement's speed.",
    "fx|Reverb|wet": "Sets the reverb level.",
    "fx|Reverb|wettone": "Tilts the wet signal warm or bright.",
    "fx|Saturation|color": "Adds transformer-style second harmonic.",
    "fx|Saturation|drive": "Pushes the preamp into saturation.",
    "fx|Saturation|mix": "Blends the saturated signal in.",
    "fx|Saturation|output": "Sets the output level.",
    "fx|Saturation|output_vol": "Sets the slot's output level.",
    "fx|Transient Shaper|attack": "Enhances or softens note attacks.",
    "fx|Transient Shaper|balance": "Aims the shaping at lows or highs.",
    "fx|Transient Shaper|drive": "Saturates the shaped output.",
    "fx|Transient Shaper|fastrel": "Sets the fast detector's release.",
    "fx|Transient Shaper|gain": "Sets the output level.",
    "fx|Transient Shaper|output_vol": "Sets the slot's output level.",
    "fx|Transient Shaper|release": "Shortens or extends note tails.",
    "fx|Transient Shaper|sens": "Sets how readily transients are detected.",
    "fx|Transient Shaper|slowatt": "Sets the slow detector's attack.",
    "fx|Transient Shaper|split": "Sets where the low and high bands divide.",
    "fx|Transient Shaper|wet": "Blends the shaped signal in.",

    # -- pedal knobs.  Same stable keying as the rack effects: the tile's
    #    param ids carry a per-run slot UUID (Jeff, 2026-08-28).
    "fx|Acoustic Preamp|ambience": "Adds modeled room around the sound.",
    "fx|Acoustic Preamp|level": "Sets the pedal's output level.",
    "fx|Acoustic Preamp|notch": "Notches out the frequency that feeds back.",
    "fx|Acoustic Preamp|resonance": "Adds body resonance, adapting to your playing.",
    "fx|Acoustic Simulator|body": "Sets how deep the modeled body sounds.",
    "fx|Acoustic Simulator|level": "Sets the pedal's output level.",
    "fx|Acoustic Simulator|reverb": "Adds modeled room around the sound.",
    "fx|Acoustic Simulator|top": "Sharpens the pick attack.",
    "fx|Bass Compressor|level": "Sets the pedal's output level.",
    "fx|Bass Compressor|ratio": "Sets how hard compression squeezes.",
    "fx|Bass Compressor|release": "Sets how fast compression lets go.",
    "fx|Bass Compressor|thresh": "Compresses signal above this level.",
    "fx|Bass Driver|blend": "Blends the clipped signal against clean.",
    "fx|Bass Driver|drive": "Drives the mid and high bands into clipping.",
    "fx|Bass Driver|high": "Sets the high band's level.",
    "fx|Bass Driver|level": "Sets the pedal's output level.",
    "fx|Bass Driver|low": "Sets the clean low band's level.",
    "fx|Bass Overdrive|balance": "Blends the clipped signal against clean.",
    "fx|Bass Overdrive|gain": "Drives the whole signal into clipping.",
    "fx|Bass Overdrive|high": "Cuts or boosts the high shelf.",
    "fx|Bass Overdrive|level": "Sets the pedal's output level.",
    "fx|Bass Overdrive|low": "Cuts or boosts the low shelf.",
    "fx|Blues Drive|drive": "Drives the signal from clean to overdriven.",
    "fx|Blues Drive|level": "Sets the pedal's output level.",
    "fx|Blues Drive|tone": "Sweeps the tone dark to bright.",
    "fx|Distortion|dist": "Drives the clipper toward a square wave.",
    "fx|Distortion|level": "Sets the pedal's output level.",
    "fx|Distortion|tone": "Tilts the tone dark to bright.",
    "fx|Fuzz|boost": "Pushes a hotter signal into the fuzz.",
    "fx|Fuzz|fuzz": "Sets how hard the fuzz clips.",
    "fx|Fuzz|level": "Sets the pedal's output level.",
    "fx|High-Gain|dist": "Cascades the clipping stages for gain.",
    "fx|High-Gain|high": "Cuts or boosts the high shelf.",
    "fx|High-Gain|level": "Sets the pedal's output level.",
    "fx|High-Gain|low": "Cuts or boosts the low shelf.",
    "fx|High-Gain|mid_db": "Cuts or boosts the mid peak.",
    "fx|High-Gain|mid_hz": "Moves the mid peak's frequency.",
    "fx|NAM Pedal|blend": "Blends the captured amp against dry.",
    "fx|NAM Pedal|high": "Cuts or boosts the high shelf after the model.",
    "fx|NAM Pedal|input/drive": "Sets how hard the capture is driven.",
    "fx|NAM Pedal|low": "Cuts or boosts the low shelf after the model.",
    "fx|NAM Pedal|mid": "Cuts or boosts the mids after the model.",
    "fx|NAM Pedal|output": "Trims the output of a loud capture.",
    "fx|Noise Gate|decay": "Sets how fast the gate closes.",
    "fx|Noise Gate|threshold": "Opens the gate above this level.",
    "fx|Octave|+1": "Sets the octave-up voice's level.",
    "fx|Octave|-1": "Sets the octave-down voice's level.",
    "fx|Octave|-2": "Sets the two-octaves-down voice's level.",
    "fx|Octave|direct": "Sets the untouched signal's level.",
    "fx|Octave|range": "Tunes tracking for bass or guitar range.",
    "fx|Polyphonic Synth|depth": "Sets how deep the modulation swings.",
    "fx|Polyphonic Synth|direct": "Sets the untouched signal's level.",
    "fx|Polyphonic Synth|effect": "Sets the synth voice's level.",
    "fx|Polyphonic Synth|rate": "Sets the modulation's speed.",
    "fx|Polyphonic Synth|tone": "Opens or closes the synth voice's filter.",
    "fx|Polyphonic Synth|var": "Picks a variation within the synth type.",
    "fx|Tuner|trim": "Fine-trims the tuner's reference pitch.",
    "fx|Wah|pedal": "Sweeps the wah from heel to toe.",
}
